version: '3'
services:
  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka-network

  kafka:
    image: 'confluentinc/cp-kafka:latest'
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_USER: kafka_user
      KAFKA_PASSWORD: kafka_password
      KAFKA_MESSAGE_MAX_BYTES: 2000000000 # Giá trị này tương đương với khoảng 2GB
    ports:
      - 9092:9092
    networks:
      - kafka-network

  kafka-ui:
    image: 'provectuslabs/kafka-ui:latest'
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - kafka-network
networks:
  kafka-network:
    driver: bridge