version: '3.9'
services:
#Microservices Idetity Server
  app:
    image: identity:1.0
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - idetity-networks
  db:
    image: mariadb:10.6
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./dbdata:/var/lib/mysql
    networks:
      - idetity-networks
networks:
  idetity-networks: