version: '3.9'
services:
  app:
    image: notifycation:1.0
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - db
    networks:
      - notifycation-networks
  db:
    image: mariadb:10.6
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    volumes:
      - ./dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - notifycation-networks
networks:
  notifycation-networks: